services:
  mariadb:
    image: wodby/mariadb:$MARIADB_TAG
    container_name: "${PROJECT_NAME}_mariadb"
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql:delegated

  php:
    image: $PROJECT_NAME/php:$PHP_TAG
    build:
      context: ./var/docker/php
      args:
        PHP_TAG: $PHP_TAG
    container_name: "${PROJECT_NAME}_php"
    environment:
      DRUPAL_CONSTRAINT: $DRUPAL_CONSTRAINT
      DRUPAL_PROJECT_NAME: $DRUPAL_PROJECT_NAME
      DRUPAL_PROJECT_PATH: $DRUPAL_PROJECT_PATH
      SSMTP_MAILHUB: mailhog:1025
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S
      SIMPLETEST_BASE_URL: "http://nginx"
      SIMPLETEST_DB: "${DB_DRIVER}://${DB_USER}:${DB_PASSWORD}@${DB_HOST}/${DB_NAME}#tests_"
      MINK_DRIVER_ARGS_WEBDRIVER: '["chrome", {"browserName":"chrome","goog:chromeOptions":{"args":["--disable-gpu","--headless"]}}, "http://chrome:9515"]'
    volumes:
      - drupal:/var/www/html:cached
      - project:/var/www/project:cached
    tmpfs:
      - /tmpfs

  crond:
    image: wodby/drupal-php:$PHP_TAG
    container_name: "${PROJECT_NAME}_crond"
    environment:
      CRONTAB: "0 * * * * drush -r /var/www/html/web cron"
    command: sudo -E LD_PRELOAD=/usr/lib/preloadable_libiconv.so crond -f -d 0
    volumes:
    - drupal:/var/www/html:cached

  nginx:
    image: wodby/nginx:$NGINX_TAG
    container_name: "${PROJECT_NAME}_nginx"
    depends_on:
      - php
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/web
      NGINX_VHOST_PRESET: $NGINX_VHOST_PRESET
    volumes:
      - drupal:/var/www/html:cached
    labels:
      - traefik.http.routers.${PROJECT_NAME}_nginx.rule=Host(`${PROJECT_BASE_URL}`)
      # HTTPS
      - traefik.http.middlewares.${PROJECT_NAME}_nginx_https.redirectscheme.scheme=https
      - traefik.http.routers.${PROJECT_NAME}_nginx.entrypoints=web
      - traefik.http.routers.${PROJECT_NAME}_nginx.middlewares=${PROJECT_NAME}_nginx_https@docker
      - traefik.http.routers.${PROJECT_NAME}_nginx_https.rule=HostRegexp(`${PROJECT_BASE_URL}`)
      - traefik.http.routers.${PROJECT_NAME}_nginx_https.tls=true
      - traefik.http.routers.${PROJECT_NAME}_nginx_https.entrypoints=websecure

  mailhog:
    image: mailhog/mailhog
    container_name: "${PROJECT_NAME}_mailhog"
    labels:
    - "traefik.http.services.${PROJECT_NAME}_mailhog.loadbalancer.server.port=8025"
    - "traefik.http.routers.${PROJECT_NAME}_mailhog.rule=Host(`mailhog.${PROJECT_BASE_URL}`)"

  traefik:
    image: traefik:v2.0
    container_name: "${PROJECT_NAME}_traefik"
    command:
      --api.insecure=true
      --providers.docker
      --entryPoints.web.address=:80
      --entryPoints.websecure.address=:443
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  chrome:
    image: drupalci/webdriver-chromedriver:production
    container_name: "${PROJECT_NAME}_chrome"
    ulimits:
      core:
        soft: -1
        hard: -1
    ports:
      - "4444:4444"
      - "9515:9515"
    entrypoint:
      - chromedriver
      - "--log-path=/tmp/chromedriver.log"
      - "--verbose"
      - "--whitelisted-ips="

volumes:
  database:
    name: "${PROJECT_NAME}_database"
  drupal:
    name: "${PROJECT_NAME}_drupal"
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/var/drupal
      o: bind
  project:
    name: "${PROJECT_NAME}_project"
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/project
      o: bind
